title: 罐头人 canHEAD
email: hi@canhead.xyz
description: ""
baseurl: ""
url: "https://canhead.xyz"
show_excerpts: true
twitter_username: virtcanhead
github_username:  virtcanhead

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

minima:
    date_format: "%Y-%m-%d %H:%M"
