title: 罐头人canHEAD
lang: zh-CN
email: aGlAY2FuaGVhZC54eXo=
description: ""
baseurl: ""
url: "https://canhead.xyz"
show_excerpts: true
twitter_username: virtcanhead
github_username:  virtcanhead

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

minima:
    date_format: "%Y-%m-%d %H:%M"
