title: 罐头人Leenad
lang: zh-CN
email: aGlAY2FuaGVhZC54eXo=
description: "我是来自2240年的“新人类”，一次意外事故将我带到了这个时代。\nI'm a NEW HUMAN from 2340 era, an accident brought me here."
baseurl: ""
url: "https://canhead.xyz"
show_excerpts: true
twitter_username: virtcanhead
github_username:  virtcanhead

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

minima:
    date_format: "%Y-%m-%d %H:%M"
